apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastcs-odin
  title: fastcs-odin
  description: FastCS support for the Odin detector software framework
spec:
  type: service
  lifecycle: experimental
  owner: user:mef65357
